// <auto-generated />
using System;
using ApiTransporte.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiTransporte.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610205110_AgregarNombreRepuesto")]
    partial class AgregarNombreRepuesto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ApiTransporte.Models.Reporte", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LugarCompra")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreRepuesto")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoReporte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorRepuesto")
                        .HasColumnType("TEXT");

                    b.HasKey("IdReporte");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Reporte");
                });

            modelBuilder.Entity("ApiTransporte.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstadoDpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoExtintor")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoRevision")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaProximaMantencion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaRevisionTecnica")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaUltimaMantencion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdConductor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProximoKilometraje")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdVehiculo");

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("ApiTransporte.Models.Reporte", b =>
                {
                    b.HasOne("ApiTransporte.Models.Vehiculo", "Vehiculo")
                        .WithMany("Reportes")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("ApiTransporte.Models.Vehiculo", b =>
                {
                    b.Navigation("Reportes");
                });
#pragma warning restore 612, 618
        }
    }
}
